"""Подсистема визуализации: layout.json, геометрия, синхронизация с БД."""
from internal.layout.geometry import (
    CANVAS_HEIGHT,
    CANVAS_WIDTH,
    OPEN_ZONE_PAD,
    adjust_rect_from_walls,
    clamp_rect_in_parent,
    clamp_rect_to_floor,
    desks_overlap_each_other,
    find_place_overlap,
    fit_open_zone_bounds,
    nudge_desks_from_walls,
    project_layout_positions,
    rect_overlaps_walls,
    validate_place_rect,
    zone_overlaps_other_desks,
)
from internal.layout.repository import LayoutRepository
from internal.layout.store import (
    add_door,
    add_place_to_layout,
    add_wall,
    delete_door,
    delete_wall,
    get_layout_place_meta,
    get_place_geometry,
    load_doors,
    load_layout,
    load_walls,
    migrate_rooms_to_spaces_in_layout,
    move_container_with_children,
    move_door,
    move_wall,
    reload_layout,
    remove_place_from_layout,
    resize_place,
    rotate_place,
    save_doors,
    save_place_category_in_layout,
    save_place_geometry,
    save_place_zone_in_layout,
    save_walls,
    sync_wall_bound_places,
)
from internal.layout.sync import (
    apply_place_location_zone,
    auto_detect_place_parents_in_layout,
    create_open_zone_from_desks,
    default_location_code_for_floor,
    ensure_place_parent_links,
    generate_place_code,
    infer_floor_from_location_code,
    migrate_legacy_place_codes,
    place_allows_child_desks,
    place_allows_layout_items,
    rename_place_code,
    resolve_place_id,
    sync_location_floors_from_layout,
    sync_parent_ids_from_layout,
    sync_place_by_code,
    sync_place_locations_from_layout,
    sync_place_parents_from_layout,
    wrap_orphan_desks_in_open_spaces,
)

__all__ = [
    'CANVAS_HEIGHT', 'CANVAS_WIDTH', 'OPEN_ZONE_PAD', 'LayoutRepository',
    'add_door', 'add_place_to_layout', 'add_wall', 'adjust_rect_from_walls',
    'apply_place_location_zone', 'auto_detect_place_parents_in_layout',
    'clamp_rect_in_parent', 'clamp_rect_to_floor', 'create_open_zone_from_desks',
    'default_location_code_for_floor', 'delete_door', 'delete_wall',
    'desks_overlap_each_other', 'ensure_place_parent_links', 'find_place_overlap',
    'fit_open_zone_bounds', 'generate_place_code', 'get_layout_place_meta',
    'get_place_geometry', 'infer_floor_from_location_code', 'load_doors',
    'load_layout', 'load_walls', 'migrate_legacy_place_codes',
    'migrate_rooms_to_spaces_in_layout', 'move_container_with_children',
    'move_door', 'move_wall', 'nudge_desks_from_walls', 'place_allows_child_desks',
    'place_allows_layout_items', 'project_layout_positions', 'rect_overlaps_walls',
    'reload_layout', 'remove_place_from_layout', 'rename_place_code',
    'resize_place', 'resolve_place_id', 'rotate_place', 'save_doors',
    'save_place_category_in_layout', 'save_place_geometry', 'save_place_zone_in_layout',
    'save_walls', 'sync_location_floors_from_layout', 'sync_parent_ids_from_layout',
    'sync_place_by_code', 'sync_place_locations_from_layout',
    'sync_place_parents_from_layout', 'sync_wall_bound_places',
    'validate_place_rect', 'wrap_orphan_desks_in_open_spaces',
    'zone_overlaps_other_desks',
]
